### PR TITLE
Update site 

### PR DESCRIPTION
**Pull request by satra**

### CODE REVIEW

**Comment by satra** [comment]
@dnkennedy, @chaselgrove -  i'll let you merge this when you have clarified things. if you need to see the site in action, it's rendered here: http://satra.cogitatum.org/repronim.github.io/

**Comment by satra** [comment]
and i'll try to see if i can delete all the unnecessary images.

**Comment by yarikoptic** [comment]
Could this one be merged??? I am getting some kind of allergy to the current one ;-)

**Comment by chaselgrove** [comment]
There's still work to do but I guess there's no sense in waiting for perfection before getting this much up!

As far as I'm concerned, further changes can be pushed directly (but don't have to be).  We'll want to be more agile with (for example) content changes.

**Pull request merged**
